version: '3.7'

services:
  app:
    image: ${COMPOSE_PROJECT_NAME}_app:${DOCKER_BUILD_MODE}
    build:
      context: ${DOCKER_BUILD_CONTEXT_DIR}
      dockerfile: docker/app/app.Dockerfile
      args:
        - HTTP_PROXY=${APP_HTTP_PROXY}
        - HTTPS_PROXY=${APP_HTTPS_PROXY}
        - NO_PROXY=${APP_NO_PROXY}
        - BUILD_MODE=${DOCKER_BUILD_MODE}
        - TIMEZONE=${TIMEZONE}
    restart: always
    environment:
      - CONTAINER_ROLE=app
